### ISSUE TITLE
Not able to install subplex in R3.6.2.   

### ISSUE THREAD

**Issue by franciscorichter** [kingaa/subplex#1]
Hi,

I have been trying to install the package in few machines, but I am not able to install it. This is the last part of the error. Do you know what could I do to install it again?
```
/usr/bin/ld: cannot find -lAtpSigHandler
/usr/bin/ld: cannot find -lAtpSigHCommData
collect2: error: ld returned 1 exit status
make: *** [/users/frichter/easybuild/daint/broadwell/software/R/3.6.2-CrayGNU-19.10/lib64/R/share/make/shlib.mk:6: subplex.so] Error 1
ERROR: compilation failed for package ‘subplex’
* removing ‘/users/frichter/easybuild/daint/broadwell/software/R/3.6.2-CrayGNU-19.10/lib64/R/library/subplex’

The downloaded source packages are in
	‘/tmp/RtmphTcCvo/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("subplex", repos = "http://kingaa.github.io/") :
  installation of package ‘subplex’ had non-zero exit status
```

**Comment by kingaa** [comment]
It would be useful to know more about the computing environment, e.g., OS, compiler suite.

Are you attempting to install from source?  If so, have you been able to install other packages requiring compilation successfully?

**Comment by franciscorichter** [comment]
It is in a linux enviroment, I am trying to install it in daint (https://en.wikipedia.org/wiki/Piz_Daint_(supercomputer)). 

I have no problem installing other packages.

**Comment by kingaa** [comment]
I know nothing about daint.  The problem looks to be something to do with the compilation.  Can you confirm specifically that you've installed other packages that require compilation?

**Comment by franciscorichter** [comment]
Oh, probably you are right. I have only installed packages from cran but I don't think I have installed other packages that requires compilation. I tried in another computer cluster and I cannot install subplex there either. Should I do an extra step to install it given that it requires compilation?

**Comment by kingaa** [comment]
No, it *should* work out of the box, i.e., installation from source automatically does the compilation, but your compilers may be somewhat nonstandard, because highly tuned to your HPC environment.  Most HPC systems I've worked on offer a range of different compilers, since some software works better (or only) with some.  If you look at, e.g., https://cran.r-project.org/web/checks/check_results_subplex.html, you'll see that CRAN checks all packages against a range of OS/compiler combinations, but the range is restricted to the most common choices, and doesn't include many popular HPC options, to say nothing of the rare and idiosyncratic ones....

Have you tried to build **R** from source?  If not, I predict that would prove highly instructive.  It uses standard `autoconf` tools to customize itself to your system before attempting compilation.  Once you get it working, and it often works on first try, it does not take very long for the build to complete.  

Other recommendation: talk to your system administrator for advice.  There's also R-sig-hpc, where you could ask for help.

**Comment by kingaa** [comment]
P.S.  All this is based on noticing
```
/usr/bin/ld: cannot find -lAtpSigHandler
/usr/bin/ld: cannot find -lAtpSigHCommData
```
in the error messages.  These errors are the linker complaining that it can't find certain libraries.  These libraries have nothing to do with **subplex**.  A quick google search leads me to suspect they are specific to Cray systems....

**Comment by franciscorichter** [comment]
Well, I have also issues installing subplex in my personal computer. This is an macOS10.15.3. The error I get there is

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [subplex.so] Error 1
ERROR: compilation failed for package ‘subplex’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/subplex’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/subplex’
Error: Failed to install 'subplex' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_r/_60qgb2n0hj4n8zm3_h35rz00000gn/T//Rtmp0duPLe/filed1408f17d5/subplex_1.6.tar.gz’ had non-zero exit status

**Comment by kingaa** [comment]
http://kingaa.github.io/mac-fortran.html

You can replace **pomp** installation with **subplex** installation.

**Comment by franciscorichter** [comment]
oh, that actually solved the problem in mac. I will try to figure out how to install subplex in the cluster then, I did manage to install it there in the past, so I do not get why it is not possible to do it with newer versions of subplex. In any case, thank you very much for all your help.

**Comment by kingaa** [comment]
FWIW, I doubt anything has changed in **subplex** in a very long time that would affect ability to compile on a generic system.  More plausible hypothesis is that your local system has changed.

Will close this issue now: feel free to re-open if necessary.
